name: Deploy Project

on:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:
    branches:
      - master
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Update submodules (fallback in case of manual cloning)
        run: |
          git submodule sync
          git submodule update --init --recursive

      - name: Generate configuration for bootch
        run: |
          echo "memcached_host: memcached" > bootch/cfg.yaml
          echo "memcached_port: 11211" >> bootch/cfg.yaml
          echo "cache_expiration: 200000" >> bootch/cfg.yaml

      - name: Generate .env file for eliborate
        run: cp eliborate/configs/.example.env eliborate/configs/.env

      - name: Build and deploy with Docker Compose
        run: docker compose up --build -d
